// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package iris_randomforest.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PostProcessor extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Parameter;
	private iris_randomforest.proxies.ML_Output_Entity_Iris_RF_ML_Model Parameter;

	public PostProcessor(IContext context, IMendixObject Parameter)
	{
		super(context);
		this.__Parameter = Parameter;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Parameter = this.__Parameter == null ? null : iris_randomforest.proxies.ML_Output_Entity_Iris_RF_ML_Model.initialize(getContext(), __Parameter);

		// BEGIN USER CODE
		if (Parameter.getOutput_label() == 0) {
			return "Setosa";
		} else if (Parameter.getOutput_label() == 1) {
			return "Versicolour";
		} else
			return "Virginica";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PostProcessor";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
