// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package iris_randomforest.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.mlkit.MLKit;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PreProcessor extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Parameter;
	private iris_randomforest.proxies.Iris Parameter;

	public PreProcessor(IContext context, IMendixObject Parameter)
	{
		super(context);
		this.__Parameter = Parameter;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Parameter = this.__Parameter == null ? null : iris_randomforest.proxies.Iris.initialize(getContext(), __Parameter);

		// BEGIN USER CODE
		// convert entity object to float array
		float[] inputFeature = new float[4];
		inputFeature[0] = Parameter.getsepalLength().floatValue();
		inputFeature[1] = Parameter.getsepalWidth().floatValue();
		inputFeature[2] = Parameter.getpetalLength().floatValue();
		inputFeature[3] = Parameter.getpetalWidth().floatValue();

		// convert input feature array to base 64
		final InputStream is = MLKit.toInputStream(inputFeature);
		final String base64 = MLKit.toBase64(is);
		
		// create output entity object
		final IMendixObject outputObject = Core.instantiate(getContext(), "Iris_RandomForest.ML_Input_Entity_Iris_RF_ML_Model");
		outputObject.setValue(getContext(), "Float_input", base64);
		return outputObject;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PreProcessor";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
