// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package iris_ensemble.actions;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class VoteForIrisClass extends CustomJavaAction<java.lang.String>
{
	private java.lang.String irisClass1;
	private java.lang.String irisClass2;
	private java.lang.String irisClass3;

	public VoteForIrisClass(IContext context, java.lang.String irisClass1, java.lang.String irisClass2, java.lang.String irisClass3)
	{
		super(context);
		this.irisClass1 = irisClass1;
		this.irisClass2 = irisClass2;
		this.irisClass3 = irisClass3;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		List<String> voteList = Arrays.asList(irisClass1, irisClass2, irisClass3);
		return voteList
			.stream()
			.collect(Collectors.groupingBy(Function.identity(), Collectors.counting()))
			.entrySet()
		    .stream()
		    .max(Map.Entry.comparingByValue()).get().getKey();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "VoteForIrisClass";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
